#=============================================================================
# Desc: Just for tuoyu's spacevim configuration
# Author: tuoyu.zhang<tuoyu.zhang@gmail.com>
# Date: 2022-11-22
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    #colorscheme = "gruvbox"
    colorscheme = "NeoSolarized"
    #colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

    # self setting for SpaceVim
    default_indent = 4
    relativenumber = false
    spacevim_default_indent = 4
    enable_filetree_gitstatus = true

    # auto complete options
    auto_complete_method = "deoplete"
    snippet_engine = "neosnippet"

    # checker options
    lint_engine = "neomake"


[[layers]]
    name = "ui"

# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"

[[layers]]
    name = "checkers"

# format model
[[layers]]
    name = "format"
    format_on_save = true


[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

# add custmer plugin

# add colorscheme layers
[[layers]]
    name = "colorscheme"

# colorizer lilydjwg/colorizer
[[custom_plugins]]
    repo = "lilydjwg/colorizer"
    merged = false

[[custom_plugins]]
    repo = "mhartington/oceanic-next"
    merged = false
[[custom_plugins]]
    repo = "lifepillar/vim-solarized8"
    merged = false


## --- Different language support ---
# add c++/c development environment
[[layers]]
    name = "lang#c"
    enable_clang_syntax_highlight = true
    clang_executable = "/usr/bin/clang"
    clang_flag = ['-I/usr/include']
    [layer.clang_std]
        c = "c11"
        cpp = "c++1z"

[[layers]]
    name = "lang#go"
    enabled_linters = ['golint']

[[layers]]
    name = "lang#python"

[[layers]]
    name = "ctrlp"

[[layers]]
    name = "git"
    git_plugin = "fugitive"

[[layers]]
    name = "tmux"

[[layers]]
    name = "gtags"
    gtagslabel = "pygments"

# add lsp autocomplete
#[[layers]]
#    name = "lsp"
#    filetypes = [
#        "c",
#        "cpp",
#        "go"
#    ]
#    enabled_clients = [
#        'pyls',
#        'vim',
#        'vim-language-server',
#        'clangd',
#        'gopls'
#    ]

